{
 "title": "OpenTelemetry Collector VM",
 "description": "Visualize OpenTelemetry (OTEL) collector metrics",
 "tags": [ "charm: opentelemetry-collector" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "query_result({__name__=~\"otelcol_process_uptime.*\"})"
    }
   },
   { "name": "minstep", "label": "Min step", "query": "10s,30s,1m,5m" },
   { "name": "metric", "label": "Base metric", "query": "Rate : rate, Count : increase" },
   {
    "name": "receiver",
    "label": "Receiver",
    "query": {
     "query": "query_result(avg by (receiver) ({__name__=~\"otelcol_receiver_.+\",job=\"$job\"}))"
    }
   },
   {
    "name": "processor",
    "label": "Processor",
    "query": {
     "query": "query_result(avg by (processor) ({__name__=~\"otelcol_processor_.+\",job=\"$job\"}))"
    }
   },
   {
    "name": "exporter",
    "label": "Exporter",
    "query": {
     "query": "query_result(avg by (exporter) ({__name__=~\"otelcol_exporter_.+\",job=\"$job\"}))"
    }
   },
   {
    "name": "grouping",
    "label": "Additional groupping",
    "query": "None (basic metrics) :  , By transport (detailed metrics) : \\,transport, By service instance id : \\,service_instance_id"
   },
   {
    "name": "suffix_total",
    "label": "Suffix _total",
    "query": {
     "query": "query_result({__name__=~\"otelcol_process_uptime.+\",job=\"$job\"})"
    }
   },
   {
    "name": "suffix_seconds",
    "label": "Suffix _seconds",
    "query": {
     "query": "query_result({__name__=~\"otelcol_process_uptime.+\",job=\"$job\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard was created with references from [opentelemetry-collector (ID 15983)](https://grafana.com/grafana/dashboards/15983-opentelemetry-collector/)"
   }
  },
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Log Records ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of log records successfully pushed into the pipeline.\nRefused: count/rate of log records that could not be pushed into the pipeline.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (receiver, $grouping) (${metric:value}(otelcol_receiver_accepted_log_records__records_${suffix_total}{job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",receiver=~\"$receiver\"}[$__rate_interval]))",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{service_instance_id}}"
    },
    {
     "expr": "sum by (receiver, $grouping) (${metric:value}(otelcol_receiver_refused_log_records__records_${suffix_total}{job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",receiver=~\"$receiver\"}[$__rate_interval]))",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Metric Points ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of metric points successfully pushed into the pipeline.\nRefused: count/rate of metric points that could not be pushed into the pipeline.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (receiver, $grouping) (${metric:value}(otelcol_receiver_accepted_metric_points__datapoints_${suffix_total}{job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",receiver=~\"$receiver\"}[$__rate_interval]))",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{service_instance_id}}"
    },
    {
     "expr": "sum by (receiver, $grouping) (${metric:value}(otelcol_receiver_refused_metric_points__datapoints_${suffix_total}{job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",receiver=~\"$receiver\"}[$__rate_interval]))",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Spans ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of spans successfully pushed into the pipeline.\nRefused: count/rate of spans that could not be pushed into the pipeline.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (receiver, $grouping) (${metric:value}(otelcol_receiver_accepted_spans__spans_${suffix_total}{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{service_instance_id}}"
    },
    {
     "expr": "sum by (receiver, $grouping) (${metric:value}(otelcol_receiver_refused_spans__spans_${suffix_total}{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{service_instance_id}}"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Logs Records ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of log records successfully pushed into the next component in the pipeline.\nRefused: count/rate of log records that were rejected by the next component in the pipeline.\nDropped: count/rate of log records that were dropped",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (processor, $grouping) (${metric:value}(otelcol_processor_incoming_items__items_${suffix_total}{job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",otel_signal=\"logs\",processor=~\"$processor\"}[$__rate_interval]))",
     "legendFormat": "Incoming: {{processor}} {{service_instance_id}}"
    },
    {
     "expr": "0 - sum by (processor, $grouping) (${metric:value}(otelcol_processor_outgoing_items__items_${suffix_total}{job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",otel_signal=\"logs\",processor=~\"$processor\"}[$__rate_interval]))",
     "legendFormat": "Outgoing: {{processor}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Metric Points ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of metric points successfully pushed into the pipeline.\nRefused: count/rate of metric points that could not be pushed into the pipeline.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (processor, $grouping) (${metric:value}(otelcol_processor_incoming_items__items_${suffix_total}{job=\"$job\",otel_signal=\"metrics\",processor=~\"$processor\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "Incoming: {{processor}} {{service_instance_id}}"
    },
    {
     "expr": "0 - sum by (processor, $grouping) (${metric:value}(otelcol_processor_outgoing_items__items_${suffix_total}{job=\"$job\",otel_signal=\"metrics\",processor=~\"$processor\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "Outgoing: {{processor}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Spans ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of spans successfully pushed into the next component in the pipeline.\nRefused: count/rate of spans that were rejected by the next component in the pipeline.\nDropped: count/rate of spans that were dropped",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (processor, $grouping) (${metric:value}(otelcol_processor_incoming_items__items_${suffix_total}{job=\"$job\",otel_signal=\"traces\",processor=~\"$processor\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "Incoming: {{processor}} {{service_instance_id}}"
    },
    {
     "expr": "0 - sum by (processor, $grouping) (${metric:value}(otelcol_processor_outgoing_items__items_${suffix_total}{job=\"$job\",otel_signal=\"traces\",processor=~\"$processor\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "Outgoing: {{processor}} {{service_instance_id}}"
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Log Records ${metric:text}",
   "type": "timeseries",
   "description": "Sent: count/rate of log records successfully sent to destination.\nEnqueue: count/rate of log records failed to be added to the sending queue.\nFailed: count/rate of log records in failed attempts to send to destination.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (exporter, $grouping) (${metric:value}(otelcol_exporter_sent_log_records__records_${suffix_total}{exporter=~\"$exporter\",job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "Sent: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum by (exporter, $grouping) (${metric:value}(otelcol_exporter_enqueue_failed_log_records__records_${suffix_total}{exporter=~\"$exporter\",job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "Enqueue: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum by (exporter, $grouping) (${metric:value}(otelcol_exporter_send_failed_log_records__records_${suffix_total}{exporter=~\"$exporter\",job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "Failed: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Metric Points ${metric:text}",
   "type": "timeseries",
   "description": "Sent: count/rate of metric points successfully sent to destination.\nEnqueue: count/rate of metric points failed to be added to the sending queue.\nFailed: count/rate of metric points in failed attempts to send to destination.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (exporter, $grouping) (${metric:value}(otelcol_exporter_sent_metric_points__datapoints_${suffix_total}{exporter=~\"$exporter\",job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "Sent: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum by (exporter, $grouping) (${metric:value}(otelcol_exporter_enqueue_failed_metric_points__datapoints_${suffix_total}{exporter=~\"$exporter\",job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "Enqueue: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum by (exporter, $grouping) (${metric:value}(otelcol_exporter_send_failed_metric_points__datapoints_${suffix_total}{exporter=~\"$exporter\",job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "Failed: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Spans ${metric:text}",
   "type": "timeseries",
   "description": "Sent: count/rate of spans successfully sent to destination.\nEnqueue: count/rate of spans failed to be added to the sending queue.\nFailed: count/rate of spans in failed attempts to send to destination.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (exporter, $grouping) (${metric:value}(otelcol_exporter_sent_spans__spans_${suffix_total}{exporter=~\"$exporter\",job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "Sent: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum by (exporter, $grouping) (${metric:value}(otelcol_exporter_enqueue_failed_spans__spans_${suffix_total}{exporter=~\"$exporter\",job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "Enqueue: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum by (exporter, $grouping) (${metric:value}(otelcol_exporter_send_failed_spans__spans_${suffix_total}{exporter=~\"$exporter\",job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "Failed: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Exporter Queue Usage",
   "type": "timeseries",
   "description": "Monitor the saturation level of each exporter queue by calculating the ratio of the current queue size against its maximum configured capacity, representing how \"full\" the buffer is from 0% (empty) to 100% (full).",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (exporter, $grouping) (otelcol_exporter_queue_size__batches{exporter=~\"$exporter\",job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}) / min by (exporter, $grouping) (otelcol_exporter_queue_capacity{exporter=~\"$exporter\",job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "Queue capacity usage: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  { "title": "Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Total CPU user and system time in percentage",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (job, $grouping) (rate(otelcol_process_cpu_seconds${suffix_total}{job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]) * 100)",
     "legendFormat": "Max CPU usage {{service_instance_id}}"
    },
    {
     "expr": "avg by (job, $grouping) (rate(otelcol_process_cpu_seconds${suffix_total}{job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]) * 100)",
     "legendFormat": "Avg CPU usage {{service_instance_id}}"
    },
    {
     "expr": "min by (job, $grouping) (rate(otelcol_process_cpu_seconds${suffix_total}{job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]) * 100)",
     "legendFormat": "Min CPU usage {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Total Runtime Sys Memory",
   "type": "timeseries",
   "description": "Total bytes of memory obtained from the OS (see 'go doc runtime.MemStats.Sys')",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (job, $grouping) (otelcol_process_runtime_total_sys_memory_bytes{job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "Max Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "avg by (job, $grouping) (otelcol_process_runtime_total_sys_memory_bytes{job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "Avg Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "min by (job, $grouping) (otelcol_process_runtime_total_sys_memory_bytes{job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "Min Memory RSS {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Uptime by Service Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (service_instance_id) (otelcol_process_uptime${suffix_seconds}${suffix_total}{job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",service_instance_id=~\".*\"})",
     "legendFormat": "Service instance uptime: {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Service Instance Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (service_instance_id, service_name, service_version) (otelcol_process_uptime${suffix_seconds}${suffix_total}{job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",service_instance_id=~\".*\",service_version=\".+\"}) or max by (service_instance_id, service_name, service_version) (otelcol_process_uptime${suffix_seconds}${suffix_total}{job=\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",service_instance_id=~\".*\"} * on (job, instance) group_left (service_version) (target_info{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"} * on (job, instance) group_left () label_replace(target_info{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}, \"service_instance_id\", \"$1\", \"instance\", \"(.*)\")))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}